apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: azzu-banking-web
  namespace: azzu-web-dev
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: azzu-banking-web
